### PR TITLE
Stripe v3

### PR DESCRIPTION
**Pull request by lolmx**
Use stripe v3, handle SCA

### CODE REVIEW

**Comment by dzschille** [comment]
Hi @lolmx , can you use some help here? I could test it. Or do you have an other idea?

**Comment by lolmx** [comment]
Hey @dzschille !

I was busy, I'll continue next week, but basically i'll just adds some tests, I'm pretty satisfied as a first version :)

Any help is appreciated of course 👍

**Comment by dzschille** [comment]
@lolmx thanks. I will test it in my application this week.

**Comment by lolmx** [comment]
I try to finish this pr today, then i'll merge and tag it to avoid a dev dependency in project's composer.
After that i'll pr that to payum repository.
If you have any feedback in between merging on master and payum's master feel free to open issues here :)

**Comment by lolmx** [comment]
@dzschille I'm testing with [those ones](https://stripe.com/docs/payments/payment-intents/migration#testing), all same but one, i'll try with the `4000 0038 0000 0446` card too now 👍

**Comment by dzschille** [comment]
@lolmx has anything changed in the setup or can i just follow https://github.com/Payum/Payum/blob/master/docs/stripe/checkout.md ?

**Comment by lolmx** [comment]
Nothing changed, only thing is to add `'sca_flow' => true` in your config

**Comment by lolmx** [comment]
Pull request merged, I do not delete branch so if you're using it you won't have any problems.
I released a [new version](https://github.com/lolmx/Stripe/releases/tag/1.6.0).
I'll pr to payum main repository later.
If you have any feedback feel free to open an issue :)

**Comment by dzschille** [comment]
@lolmx i get an error:
```
Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException:
"Attempted to load class "PaymentIntent" from namespace "Stripe". 
Did you forget a "use" statement for another namespace?" at /application/vendor/payum/stripe/Payum/Stripe/Action/Api/CreatePaymentIntentAction.php line 72
```
I placed you directory "Stripe" inside my "vendor/payum/stripe/Payum/" after i deleted the original  directory "Stripe" in there. Then i dumped the autoloader:
`composer dump-autoload`
I also added the `'sca_flow' => true` to my configuration.
Have i forgotten something?

**Comment by lolmx** [comment]
You need to require stripe-php ^6
They added PaymentIntent api in something like 6.15
Should be just that :)
I'll add a class_exist check with sca_flow param to throw an explicit error

**Comment by j0r1s** [comment]
Hello @lolmx !

Thanks for your work, I wanted to give it a shot on my e-commerce project based on sylius but I'm encountering some dependencies problems :
```
$ composer require Payum/Stripe:"^1.6"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sylius/sylius v1.6.0 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - sylius/sylius v1.6.0 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - sylius/sylius v1.6.0 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - don't install payum/stripe 1.6.0|remove payum/payum 1.5.1
    - don't install payum/payum 1.4.0|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.1|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.2|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.3|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.0|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.1|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.1|don't install payum/stripe 1.6.0
    - Installation request for payum/stripe ^1.6 -> satisfiable by payum/stripe[1.6.0].
    - Installation request for sylius/sylius (locked at v1.6.0, required as ^1.5) -> satisfiable by sylius/sylius[v1.6.0].
```

Any idea on how to fix that ?

**Comment by lolmx** [comment]
Hello @j0r1s!
Can you dump you composer.json? Looks like some packages do not accept a payum update.
I forked repository from master@1.5.1

**Comment by Prometee** [comment]
Sylius require `payum/payum:"^1.4"` so we can't install a "sub composer package" or there is a trick to add to made "payup/payum" accept your fork ?

**Comment by j0r1s** [comment]
Sorry for the delay on my answer @lolmx .
As @Prometee stated, it's a sub-dependency from sylius, I'm not directly requiring payum.

But here is my _cleaned_ `composer.json` :
```json
{
    "require": {
        "php": "^7.2",
        "payum/stripe": "^1.5",
        "stripe/stripe-php": "^6",
        "sylius/sylius": "^1.5",
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/lolmx/Stripe.git"
        }
    ]
}
```

But if I understand correctly, the problem comes from `sylius/sylius` `composer.json` (or one of its dependencies) :
```json
{
    "name": "sylius/sylius",
    "require": {
        "payum/payum": "^1.4",
        "payum/payum-bundle": "^2.2",
    },
    "require-dev": {
        "stripe/stripe-php": "^4.1",
    },
    "replace": {
        "sylius/payum-bundle": "self.version",
    },
}
```

I've tried to only include what's related to payum.

And for the record, here is the composer error when requiring your `Payum/Stripe` fork :
```bash
Problem 1
    - Conclusion: don't install payum/stripe 1.6.1
    - sylius/sylius v1.5.2 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - sylius/sylius v1.5.2 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - sylius/sylius v1.5.2 requires payum/payum ^1.4 -> satisfiable by payum/payum[1.5.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0].
    - don't install payum/stripe 1.6.0|remove payum/payum 1.5.1
    - don't install payum/payum 1.4.0|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.1|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.2|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.4.3|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.0|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.1|don't install payum/stripe 1.6.0
    - don't install payum/payum 1.5.1|don't install payum/stripe 1.6.0
    - Installation request for payum/stripe ^1.6 -> satisfiable by payum/stripe[1.6.0, 1.6.1].
    - Installation request for sylius/sylius (locked at v1.5.2, required as ^1.5) -> satisfiable by sylius/sylius[v1.5.2].
```

Thanks for help ! (If you'd rather move this discussion somewhere else, let me know.)

**Comment by dzschille** [comment]
@Prometee @j0r1s as a workaround for testing you could replace the directory _vendor/payum/stripe/Payum/Stripe_ manually with the forked code which you clone to a directory outside your project and copy from there.

**Comment by Prometee** [comment]
@dzschille that was my second option to test it but if we have to go to prod on the 15th September we will need a composer way of doing it. Or maybe override sources after `composer install` with a `"post-install-cmd"` script :(

**Comment by dzschille** [comment]
@Prometee i think your app update hasn't to be ready in 4 days: 
https://support.stripe.com/questions/strong-customer-authentication-sca-enforcement-date

@lolmx could it be a workaround for the payum version conflict if you use just a patch update in the version number? 1.5.2 instead 1.6.0?

**Pull request merged**
